### ISSUE TITLE
Error: Failed. `An error occurred. Please try again later.` 

### ISSUE THREAD

**Issue by puneetkathar1** [marcolivierbouch/OpenAssistantGPT#129]
**Describe the bug**
When I go to chatbot and start chatting, anything I ask it gives this reply `An error occurred. Please try again later.` I think it might be due the the waitForRun function in `/api/chatbots/[chatbotId]/chat/route.ts` is returning run status as failed.

But how can I fix it?

**To Reproduce**
1. Go to`https://www.openassistantgpt.io/dashboard/chatbots/`
2. Click on a Chatbot
3. Start Chatting with it, ask any question
5. See error

**Expected behavior**
Should return the response of the question asked

**Screenshots**
![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/73285338/57b88e07-2049-4ad6-a04b-8b7963c95e72)

**Comment by puneetkathar1** [comment]
@marcolivierbouch there can be a possibility that its happening because of OpenAI server issue, because day before yesterday it was working fine. Only since yesterday I'm getting this issue.
Can you please confirm if this might be an issue?

**Comment by marcolivierbouch** [comment]
Hi @puneetkathar1 I have tried to reproduce your issue but I can't figure out why yet. Maybe like you said it was an issue with OpenAI.

**Comment by puneetkathar1** [comment]
@marcolivierbouch yes, its resolved after I added billing details to openai.
