### ISSUE TITLE
Scrollbar, more customizations and clickable link

### ISSUE THREAD

**Issue by SamuelChabal** [marcolivierbouch/OpenAssistantGPT#133]
Thanks for the work !

I try the version on https://www.openassistantgpt.io/, but a few points :
- I don't see scrollbar when the message exceeds the window size
- I need more customizations, replace "Chat with us" and "Type a message" by another language
- It would be great to be able to click on the links in a message

**Comment by marcolivierbouch** [comment]
Thank you for the recommendations I will add them in my backlog!

**Comment by marcolivierbouch** [comment]
Hi @SamuelChabal, The scrollable issue is now fixed for the chatbot! :) Thank you!

**Comment by marcolivierbouch** [comment]
Hi @SamuelChabal! It is just to yet you know that the customizations that you ask for are now live with any pricing plan above FREE!

**Comment by marcolivierbouch** [comment]
Hi @SamuelChabal, links are now clickable all the underlined text are links! 
![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/29548847/a994cd17-622e-434f-9089-705867f64450)

**Comment by marcolivierbouch** [comment]
all requets are completed!-
