### ISSUE TITLE
InvalidCharacterError

### ISSUE THREAD

**Issue by jonasmikkola72** [marcolivierbouch/OpenAssistantGPT#147]
InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('rose-pine dark') contains HTML space characters, which are not valid in tokens.

Any idea why this is happening?

**Comment by jonasmikkola72** [comment]
![Skärmavbild 2024-03-02 kl  09 49 52](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/159510495/f09b1fe6-ac96-49b5-8b6a-f3c6db294963)

**Comment by marcolivierbouch** [comment]
Can you show me your code @jonasmikkola72 ?

**Comment by jonasmikkola72** [comment]
it was something with my own computer, on port 3000 i only got this error, changed to 3004

where should we add the openai key? because it seems it doesnt fetch from settings, do we need to add it to env file? 
![Skärmavbild 2024-03-02 kl  17 08 28](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/159510495/094bf4b9-58f1-4393-a07b-2edb95557a3e)

**Comment by marcolivierbouch** [comment]
> it was something with my own computer, on port 3000 i only got this error, changed to 3004
> 
> where should we add the openai key? because it seems it doesnt fetch from settings, do we need to add it to env file? ![Skärmavbild 2024-03-02 kl 17 08 28](https://private-user-images.githubusercontent.com/159510495/309521873-094bf4b9-58f1-4393-a07b-2edb95557a3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1ODIwOTIsIm5iZiI6MTcwOTU4MTc5MiwicGF0aCI6Ii8xNTk1MTA0OTUvMzA5NTIxODczLTA5NGJmNGI5LTU4ZjEtNDM5My1hMDdiLTJlZGI5NTU1N2EzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQxOTQ5NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTQ5OTY0YTEyZDA0MmVlZTA5Mzc1NTNlZDJjZDU2M2I5NzMxNjdmZDE3NmFiZTlhZmVjY2ZmODljMTgwMDU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DVuZaxQOoT23QHa3j190LdKuZniVEFQeCxMY8pUontg)

You have to configure this API Key on your account and the Settings tab. :)

**Comment by jonasmikkola72** [comment]
is there any way i can set this key to be the same always, cant i hard code this somewhere in the code?

**Comment by marcolivierbouch** [comment]
> Reference

You could update the path /api/models to return a list of hardcoded values

**Comment by cometcoreco** [comment]
im wondering the same, it doesnt fetch the models when i gonna create a bot i cant create it because i need to choose models, but i  cant fetch them, could you please take a look if you have time https://github.com/cometcoreco/copiloto

really good work though, i like it! thanks

**Comment by marcolivierbouch** [comment]
> im wondering the same, it doesnt fetch the models when i gonna create a bot i cant create it because i need to choose models, but i cant fetch them, could you please take a look if you have time https://github.com/cometcoreco/copiloto
> 
> really good work though, i like it! thanks

When fetching model you need to configure your OpenAI key in your account first and it will store the OpenAI API key in the database, please use forks when copying the repo ;P

**Comment by jonasmikkola72** [comment]
![Skärmavbild 2024-03-11 kl  21 29 23](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/159510495/c84ffde8-cb0f-4914-b241-81d96f3cfa64)

this is the error i get when i try add the openai key

**Comment by marcolivierbouch** [comment]
@jonasmikkola72 you also have to add your models in your database like this:

![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/29548847/0fe77284-cc5b-4cb3-ac59-e8c98cbd5ef7)

**Comment by jonasmikkola72** [comment]
kiiiingggg!! works!

**Comment by marcolivierbouch** [comment]
> kiiiingggg!! works!

@jonasmikkola72 can you build the setup guide and push it to this repo in the content folder?
