### ISSUE TITLE
Auto Scroll on Chat Widget

### ISSUE THREAD

**Issue by williamzebrowskI** [marcolivierbouch/OpenAssistantGPT#162]
**Is your feature request related to a problem? Please describe.**
We have the OpenAsssistantGPT in a production environment and it appears that when communication with the bot, the chat UI does not automatically scroll down to the most recent message.

**Describe the solution you'd like**
As the problem describes, I believe he solution would be to have that chatUI automatically scroll down to the most recent message in the chat.  

**Describe alternatives you've considered**
I think an alternative option is that a web developer can edit the Chat Widget code to create this autoscroll feature

**Comment by marcolivierbouch** [comment]
Hi @williamzebrowskI,

Thank you for your time. On my side im currently testing and widget is automatically scrolling in new messages. Can you share with me your website?

Thanks
