### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by jonasmikkola72** [marcolivierbouch/OpenAssistantGPT#182]
hello, could you please just in short tell us instructions on what we need to do in order to fork it

1. fork it
2. create a env file with exactly what keys?
3. npm install?

i cant get it to work i tried 10 times, the problem is that the models are not being fetched, the api key is being set because it works to upload files etc, but it doesnt work to fetch any models so i cant create any bot succesfully

**Comment by marcolivierbouch** [comment]
Hi @jonasmikkola72, yes it is in my todo list!

**Comment by jonasmikkola72** [comment]
cant you just tell me here what piece is missing in my puzzle, i have been waiting for your instructions since you said it 2 weeks ago in this thread hehe https://github.com/marcolivierbouch/OpenAssistantGPT/issues/130#issuecomment-1962671169

i tried over and over again from different computers, please just help me what i do wrong 

thanks in advance brother!

**Comment by marcolivierbouch** [comment]
First of all im doing my best to reply and I have already commented in your issue.... also it is not like you are paying for something so I don't own you anything... For the past 2 weeks im helping other clients don't worry im working....

https://github.com/marcolivierbouch/OpenAssistantGPT/issues/147
