### ISSUE TITLE
Response Message

### ISSUE THREAD

**Issue by williamzebrowskI** [marcolivierbouch/OpenAssistantGPT#183]
Apologies, this is more of a question and we are unsure if this response below we are receiving is coming from OpenAssistantGPT or from OpenAI:

For Context:
We had a lot of people test our bot at once and we are aware of the rate limits,  however, everyone received this message during that rate limit freeze:

_“Oops! An error has occurred. Please ensure that your OpenAI account is configured correctly with a valid credit card. If the issue persists, feel free to reach out to our support team for assistance. We're here to help!”_

Thanks for any confirmation!

**Comment by marcolivierbouch** [comment]
Hi @williamzebrowskI!

This error is from OpenAssistantGPT it is returned when there is an error when trying to generate an reply. So we god many error from OpenAI.

Of course there is a rate limit on the Assistant API https://platform.openai.com/docs/guides/rate-limits/usage-tiers?context=tier-free 

We got many errors from 11:30 EST to 11:50 EST today but im not sure it is from which account but it is specific to one person.

**Comment by williamzebrowskI** [comment]
Thanks for clarifying @marcolivierbouch - Is there any talk about possibly changing this message?  With our bot (and others) in a production environment, because this message can be very concerning for a real user.

**Comment by marcolivierbouch** [comment]
> Author

**Comment by marcolivierbouch** [comment]
> Thanks for clarifying @marcolivierbouch - Is there any talk about possibly changing this message? With our bot (and others) in a production environment, because this message can be very concerning for a real user.

I will make sure to change it when you use the widget!

**Comment by marcolivierbouch** [comment]
Hi @williamzebrowskI 

The feature you asked for is now live! You can now edit the error messages that will be outputed to your user where there is an issue and there is also a new tab where you can sell all of your chatbot errors.

![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/29548847/cbabf0f9-3124-42f8-b7ea-6dd2f2404f6e)
