### ISSUE TITLE
Is ChatWindow.js script not working?

### ISSUE THREAD

**Issue by Joecey** [marcolivierbouch/OpenAssistantGPT#193]
**Describe the bug**
When trying to use chatwindow.js, nothing appears on Next.js page

**To Reproduce**
1. On a Nextjs page, load the the normal chatbot by following instructions and it works fine and loads the following below
```
return (
        <main className={styles.centerDiv}>
            <Script
                src="https://www.openassistantgpt.io/chatbot.js"
                strategy="afterInteractive"
            />
            <div
                className={styles.chatOverlay}
                id="openassistantgpt-chatbot"
            ></div>
        </main>
    )
```
<img src="https://github.com/marcolivierbouch/OpenAssistantGPT/assets/84920916/a7c5d793-0984-4464-a09a-af6a4792e109" alt="drawing" width="500"/>

2. However, attempting to use ChatWindow.js results in nothing appearing
```
return (
        <main className={styles.centerDiv}>
            <Script
                src="https://www.openassistantgpt.io/chatwindow.js"
                strategy="afterInteractive"
            />
            <div
                className={styles.chatOverlay}
                id="openassistantgpt-chatbot"
            ></div>
        </main>
    )
```

**Expected behavior**
I expect a chatWindow widget similar to the OpenAssistant website
![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/84920916/abc20a82-1607-4ff5-87bc-0820e002022c)

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Browser: Chrome, Firefox

**Additional context**
Currently using Next.js 14 App router and trying to add the widget in a client component page

Thanks in advanced!!

**Comment by marcolivierbouch** [comment]
Hi @Joecey ! 

Chatwindow.js doesnt support next.js yet!

What I can recommend you would be to copy paste this component here: https://github.com/marcolivierbouch/OpenAssistantGPT/blob/main/components/chat.tsx 

Copy my components and you should be good!

**Comment by Joecey** [comment]
Thanks Marc for the quick response! Will have a go at it, thanks!
