### ISSUE TITLE
Getting empty array in api/models  api

### ISSUE THREAD

**Issue by somykoron-it** [marcolivierbouch/OpenAssistantGPT#230]
Hi I just connected to this repo with my local postgres but the issues is in this `api/model` always getting [] array as response. But in the production mode https://www.openassistantgpt.io/dashboard/new/chatbot its giving the model name. Have you added those in DB by hand or this suppose to added when a user will add a gpt key?

Also I can see there is one api available to get all the models available associated with my gpt key but why its showing only the 2 model?

**Comment by marcolivierbouch** [comment]
Hello! 

In the model table you have to add this 

![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/29548847/15ce948b-238c-4078-a4a2-1633a206f41c)
