### ISSUE TITLE
Allow "Display Link After X Chatbot Reply" to display after every message

### ISSUE THREAD

**Issue by JaredDanielJones** [marcolivierbouch/OpenAssistantGPT#255]
Having the option to either display the link after EVERY message following the submitted amount instead of just that specific message would be nice. The link could disappear when it's not the most recent message with the link displayed.

**Comment by marcolivierbouch** [comment]
Hello @JaredDanielJones !

Im currently updating the UI to make this better, custom option are acutally going to appear over the input field.

The window integration is currently done, im working on the chatbox integration now!

![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/29548847/db9b84d3-e9d1-415e-84a9-b8472a9daf90)
