### ISSUE TITLE
Hello, I want to know the OpenAssistantGPT When will support for mobile devices be available?

### ISSUE THREAD

**Issue by zhangjiuyang1993** [marcolivierbouch/OpenAssistantGPT#264]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marcolivierbouch** [comment]
Hello! 

Our chatbots already support mobile, only the dashboard that is not fully mobile compatible!

**Comment by marcolivierbouch** [comment]
What do you need excactly?

**Comment by zhangjiuyang1993** [comment]
Yes, I want to your chatbots apply into the ios and Android phone. Do your chatbots support?

**Comment by zhangjiuyang1993** [comment]
Can your chatbot be embedded into our app?

**Comment by marcolivierbouch** [comment]
Hi @zhangjiuyang1993,

Our chatbot works very well for mobile websites! But we don't have integrations for mobile applications

![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/29548847/bc5b7e8d-e437-4c5e-9389-047d472a4035)
