### ISSUE TITLE
Is there any plan to switch to assistant v2?

### ISSUE THREAD

**Issue by znnan** [marcolivierbouch/OpenAssistantGPT#270]
Hi,

firstly I would like to thank you for such a great job. I am able to run this repo locally and make it interactive via the OpenAI api. Recently, OpenAI imports the v2 version for assistant and a separate vectorStore is imported. I would like to know is there any plan to switch the v2 version? or  provides an option for user to enable v2 version in a new chatbot?

Thanks

**Comment by marcolivierbouch** [comment]
Hi @znnan,

Would love to support this. I'll get to it whenever I have the time 💪
