### ISSUE TITLE
When will you support gpt-4o?

### ISSUE THREAD

**Issue by BureauSpraakwater** [marcolivierbouch/OpenAssistantGPT#272]
I tried to manually select the model at platform.openai.com but that results in an error when using the assistant. Thanks!

**Comment by DanDans123** [comment]
same issue

**Comment by marcolivierbouch** [comment]
Hello! It is the next thing im working on!

**Comment by marcolivierbouch** [comment]
@BureauSpraakwater @DanDans123 

The new update is live and we support gpt-4o!

You can give it a try! :)
