### ISSUE TITLE
Links not properly marked up

### ISSUE THREAD

**Issue by blatka** [marcolivierbouch/OpenAssistantGPT#275]
Links from GPT Assistants are specified like this: [Link Text] (https://urlgoeshere.com/). The link rendered in the chatbot shows both the link text and URL, but it's all run together like this: Link Texthttps://urlgoeshere.com (the entire string is underlined and run together).

<img width="419" alt="Screenshot 2024-05-14 at 10 27 54 PM" src="https://github.com/marcolivierbouch/OpenAssistantGPT/assets/150701455/a1d9fee0-bbcd-4640-b022-4a354d64d83c">

I'm using gpt-4-turbo.

**Desktop (please complete the following information):**
 - OS: MacOS 14.4.1 
 - Browser : Chrome
 - Version 124.0.6367.207

I'm using the free version right now and am LOVING it!! 
Thanks

**Comment by marcolivierbouch** [comment]
![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/29548847/c215108f-e9a5-4602-ba5f-44f3d64e3c3e)

Hello we have updated the way we implement chatbot in websites I would recommend to redo the embed to website steps with our new code. In the new version the link issue is fixed! :) 

Let me know if you have any question!

**Comment by blatka** [comment]
Thank you! I tried mightily to get this to work, but the issues this new code caused:

In Chrome, the iFrame opens at the top left of my site, and the top is hidden beneath my nav header. It includes a Contact Us button that goes to your site, not mine. 

In Firefox, the iFrame opens in place as expected. I didn't recall if the Contact Us button was there. I removed it before I realized this was an issue.

I have reverted to the code I had before and will wait for the next version. I'm on the free plan now, so I'm not complaining! Thanks again.

**Comment by blatka** [comment]
Hello. I am trying this new code on my site, but it's not working. I left it installed so you can see what's going on. Here's a video of what I'm experiencing: https://app.screencastify.com/v3/watch/AsiGvaBOKQNnznSJPvR9

I tried both the method as described in the video, and I used your chatbot to ask for specific instructions. It suggested two ways (the one I show above), and adding the code into a widget using a custom HTML block. I tried this as well and got the same results.

I'll leave the code installed so you can check it out but will need to remove it as soon as you can look here: https://www.ancienttreearchive.org/

Thanks - Bill
