### ISSUE TITLE
Styling Response Text

### ISSUE THREAD

**Issue by kroboz** [marcolivierbouch/OpenAssistantGPT#283]
**Is your feature request related to a problem? Please describe.**
This is probably the easiest and most fairly-priced implementation of an OpenAI assistant chatbot. Appreciate your work on this. 

The text in the embedded iframe chatbot is really spaced out. There is padding and margins that make a short answer look very long. Since my assistant returns items as a list, the spacing is even more of an issue due to a gap before the ul starts. Here's an example: https://capture.dropbox.com/bpdti55tzvCoHid8

**Describe the solution you'd like**
I'd love to see some kind of CSS documentation where I can modify the margins/padding/space between elements

**Describe alternatives you've considered**
Since it's an iframe embed, my own stylesheet doesn't work. (Or could it, somehow?)The non-standard classes in the responses also make it hard to pin down styling. There are gaps I can't seem to find using the dev tools in my browser – gaps between elements or maybe something to do with the flex.

**Additional context**

Thanks!

**Comment by marcolivierbouch** [comment]
Hello @kroboz, thank you for the feedback I will definetly try to make the spacing smaller when we have a list!

We just removed our js integration since it causes issue with almost 50% of the integraions due to CSS conflicts we had to much support cases about this and it is always hard toe debug!

**Comment by aimachinedream** [comment]
ya the current spacing is now totally unusable.  As soon you start getting markdown and bullet points in the response, there is more white space than text.  It needs to be going in completely the opposite direction, fitting as much text as is possible in a small box.

**Comment by marcolivierbouch** [comment]
I just updated the spacing issue in the chatbot, I was using wrong tailwindcss classes! Give it a try and let me know what you think now!

**Comment by aimachinedream** [comment]
Ya much better! Thanks!! I have about 20 feature requests lol, but ya it is useable now :)

**Comment by marcolivierbouch** [comment]
Hey @aimachinedream dont hesite to send them to me by email or simply open an issue, I probably won't do all of them but if you can provide good idea that can help the project to grow I would be happy to to them.
