### ISSUE TITLE
Some way to deal with and format document references in V2 replies.

### ISSUE THREAD

**Issue by aimachinedream** [marcolivierbouch/OpenAssistantGPT#289]
These are currently not formatting at all and look like "【4:0†source】".  I have not had any luck prompting to strip these out.  Ideally we could have an option to 1st) Strip them out 2nd) Link to the actual document.

When they are displayed they should look like [1] [2] [3] etc

**Comment by marcolivierbouch** [comment]
I think i may simply be better in our case to strip out the 【4:0†source】for this chatbot! I will add this to my todo list

**Comment by marcolivierbouch** [comment]
@aimachinedream the just updated the formating to make it look better I had an issue with CSS classes on my side and im removing all 【4:0†source】 from the chatbot reply

**Comment by aimachinedream** [comment]
Ya much better. Looks nice now.  Ya perhaps one day, be interesting to put actual documents, but I really don't know exactly how that could work, so good enough for me!
