### ISSUE TITLE
contentlayer not available for Next 14? Is there a Suggested workarouind?

### ISSUE THREAD

**Issue by timstew** [marcolivierbouch/OpenAssistantGPT#304]
**Describe the bug**
During npm install I get the following error:

npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: next-contentlayer@0.3.4
npm ERR! Found: next@14.2.2
npm ERR! node_modules/next
npm ERR!   next@"^14.2.2" from the root project
npm ERR!   peer next@"^13.0.0 || ^14.0.0" from @next/third-parties@14.1.3
npm ERR!   node_modules/@next/third-parties
npm ERR!     @next/third-parties@"^14.1.3" from the root project
npm ERR!   3 more (@sentry/nextjs, next-auth, next-themes)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^12 || ^13" from next-contentlayer@0.3.4
npm ERR! node_modules/next-contentlayer
npm ERR!   next-contentlayer@"^0.3.4" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: next@13.5.6
npm ERR! node_modules/next
npm ERR!   peer next@"^12 || ^13" from next-contentlayer@0.3.4
npm ERR!   node_modules/next-contentlayer
npm ERR!     next-contentlayer@"^0.3.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

A clear and concise description of what the bug is:

I'm pretty sure this is because contentlayer doesn't work on Next 14?
I guess I'll give --legacy-peer-deps a try...

**To Reproduce**
git clone 
npm install

**Expected behavior**
No errors

**Additional context**

**Comment by marcolivierbouch** [comment]
Hi @timstew, there is no actual good fix for this! But what we do on our side is `npm i --force` it should do the trick!
