### ISSUE TITLE
Image uploading

### ISSUE THREAD

**Issue by aimachinedream** [marcolivierbouch/OpenAssistantGPT#312]
With GPT 4o there are a ton of use cases for this.  Would be really great to have.  Put it in a premium product.

**Comment by marcolivierbouch** [comment]
Definetly a feature that we want! I will try to deliver this feature soon!

**Comment by marcolivierbouch** [comment]
Hello @aimachinedream,

It is now possible to upload file and images in the chatbot in PRO plan. This one wanst easy was a good challenge but it is delivered!

![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/29548847/af805de6-866d-40c6-9f64-135085499391)


https://github.com/marcolivierbouch/OpenAssistantGPT/pull/321
