### ISSUE TITLE
Title: Add Continuous Testing for Project

### ISSUE THREAD

**Issue by vr-varad** [marcolivierbouch/OpenAssistantGPT#331]
**Is your feature request related to a problem? Please describe.**
We don't have a way to check if our code is good enough before we put it out for everyone to use. Sometimes, mistakes slip through and cause problems later on.

**Describe the solution you'd like**
We should set up something called "continuous integration" (CI) for our project. It's like having a robot check our code every time we make a change to make sure it's okay. This will help us catch mistakes early and make sure everything works smoothly.

**Describe alternatives you've considered**
Right now, we mostly rely on ourselves to test our code before sharing it. But this can be slow and we might miss things. With CI, the computer does a lot of this work for us, saving time and reducing errors.

**Additional context**
Setting up CI means we'll use tools like Jenkins, Travis CI, or GitHub Actions to automatically test our code and make sure it's up to scratch. It'll make our development process smoother and our final product more reliable for users.

**Comment by marcolivierbouch** [comment]
We are open to contribution to the repo! You can create a fork and create step for testing in the repo using vercel built-in tools!

Then you can open a PR and we will review it! :)
