### ISSUE TITLE
Max Tokens not set correctly.

### ISSUE THREAD

**Issue by aimachinedream** [marcolivierbouch/OpenAssistantGPT#342]
When setting the tokens, whatever you set for the input tokens, shows up  (after saving, leaving,  and returning to the settings) as the value for both the input and output tokens.  I'm not sure if just a UI issue, or if the value is being set incorrectly as well.

**Comment by marcolivierbouch** [comment]
Hello @aimachinedream,

Thanks for the bug report. It was a UI issue it is now fixed!
