### ISSUE TITLE
Track chat input for enhanced user experience

### ISSUE THREAD

**Issue by dhoegerlETM** [marcolivierbouch/OpenAssistantGPT#348]
**Is your feature request related to a problem? Please describe.**
We are hosting a chatbot using your framework and would like to know what our customers/users are asking for to be able to react on their requirements and pains.

**Describe the solution you'd like**
We'd like to be able to see and export the entered questions of users to the chatbot, be it from the dashboard or via some API call.

**Describe alternatives you've considered**
Hook into the chat's input form and store the entered questions in some file or data base.

**Comment by marcolivierbouch** [comment]
The easy solution for now is to enable threads in OpenAI and build a script over their api to extract everything 

https://www.openassistantgpt.io/guides/how-to-see-all-your-chatbot-threads

**Comment by marcolivierbouch** [comment]
It is in our backlog to improve messages and add export

**Comment by marcolivierbouch** [comment]
Hello @dhoegerlETM,

You can now generate JSON export for a specific time range!

https://www.openassistantgpt.io/dashboard/exports
