### ISSUE TITLE
Configurable chat input textbox

### ISSUE THREAD

**Issue by dhoegerlETM** [marcolivierbouch/OpenAssistantGPT#366]
Currently the textbox for the user's chat input is only single-line and uses not more than a max-width, even if the chat-windows is defined much larger.

As a customer I would like to configure even multiline textbox and the relative width of the chat-window.

**Comment by mattlawlis** [comment]
I am also looking for this feature.

**Comment by AdamDCostaJyre** [comment]
Yep - same here. Its particularly an issue on mobile.

**Comment by marcolivierbouch** [comment]
Will work on this next!

**Comment by marcolivierbouch** [comment]
@mattlawlis  @dhoegerlETM  @AdamDCostaJyre 

In the customization tab it is now possible to choose input style. You have default or full width. We also now use textarea so you can scroll if you have multple lines! Let me konw if all your issues are fixed!

You can go read our changelog https://www.openassistantgpt.io/changelog

![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/29548847/0fd2687d-9584-4d05-b9ad-c48924991be0)

**Comment by dhoegerlETM** [comment]
@marcolivierbouch fine, looks good now! Only, the text in the chatbot-configuration says "User Background Message Color" like the color-setting above. Please adapt the setting name as well.
