### ISSUE TITLE
API Setup: Error running assistant

### ISSUE THREAD

**Issue by Akhileshrangani4** [marcolivierbouch/OpenAssistantGPT#374]
I finally was able to set up everything locally, but When creating and running the bot locally, the API key is getting set up okay, but when I type in any messages it gives me an error, I have attached the screenshots.

filepath: \chatbotjs\src\Chat.tsx
![error chatassistant code](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/70284178/7ca1bfb1-e9f2-43e3-8619-823e38780b4b)
![error chatassistant](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/70284178/dcbc8333-2603-46ad-aca9-579fc9ab1b6a)
![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/70284178/3ba9a382-e833-4803-8b80-ffc83582fe6d)

**Comment by marcolivierbouch** [comment]
The error will be displayed in the errors section or simply add console.log...
