### ISSUE TITLE
Significant difference comparing embedded chatbot with native OpenAI assistant using file-upload

### ISSUE THREAD

**Issue by dhoegerlETM** [marcolivierbouch/OpenAssistantGPT#408]
We are using an assistant from OpenAI with quite detailed configuration, i.e. we have defined specific instructions ("context"), file_search and code_interpreter and changed the default temperature parameter.

However, when we submit the very same prompts plus attached PDF documents in your embedded chatbot and in the OpenAI assistant playground (or another Python hosting) we get a significant different result.

It seems like the attached document is only uploaded to OpenAI storage but not attached to the message-thread so that the chatbot could incorporate it's content. Or maybe you overwrite some predefined parameters of our assistant, like the context or the temperature.

Mind parameter "attachments" in following example:

```
msg_attachments.append( { "file_id": myfile.id, "tools": [ { "type": "file_search" } ] } )

client.beta.threads.messages.create(
            thread_id=mythread_id,
            role="user",
            content=prompt,
            attachments=msg_attachments
        )
```

Please check on your side and report back.

**Comment by dhoegerlETM** [comment]
@marcolivierbouch from priority viewpoint this would be the most important for us. Just if you have to decide on your next topic. Thanks a lot!

**Comment by marcolivierbouch** [comment]
Hi @dhoegerlETM, we have a PR opened, it should be merged soon!

https://github.com/marcolivierbouch/OpenAssistantGPT/pull/414

**Comment by marcolivierbouch** [comment]
It is in production! Let me know if you have any issue!

The results are already better when using a file!

**Comment by dhoegerlETM** [comment]
Can confirm that the uploaded files are now considered correctly and thus the answers are valid now!

Only mind @marcolivierbouch that the uploaded file now remains in the OpenAI storage, which wasn't the case before.

**Comment by marcolivierbouch** [comment]
This is definetly something we need to take a look at next! We need to make sure to clean our clients OpenAI account!
