### ISSUE TITLE
Vercel Deployment issue: Builder returned invalid maxDuration value

### ISSUE THREAD

**Issue by Akhileshrangani4** [marcolivierbouch/OpenAssistantGPT#411]
So I have finally figured out how to deploy OpenAssistantGPT locally, and it works great, kudos to you, creator!

I am using vercel for deploying my app, but when I deploy it, I have solved all the build errors except this one where vercel tells me to set the maxDuration according to my plan. Now, I understand the need for this, but I am not sure where and which functions I am supposed to limit the maxDuration for.
![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/70284178/c0cd7f7a-e26d-4b69-a4aa-4c0bde1787ab)
![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/70284178/f8294523-5905-4b6b-909f-967b384be230)

**Comment by marcolivierbouch** [comment]
Hello, you have to buy Pro plan in Vercel or you change the MaxDuration by 60 on functions that have a too hight timeout. :) Just du a search you should be able to find a few

**Comment by Akhileshrangani4** [comment]
Thanks for the help, @marcolivierbouch

**Comment by Akhileshrangani4** [comment]
Also, can you please tell me where are you hosting it? Since I will have to work with higher MaxDuration, I am thinking of different hosting solutions.

**Comment by marcolivierbouch** [comment]
It is hosted in Vercel

@Akhileshrangani4
