### ISSUE TITLE
Copying and pasting text with breaks

### ISSUE THREAD

**Issue by mattlawlis** [marcolivierbouch/OpenAssistantGPT#421]
When you paste text into the chatbot message field and click send, it does not retain the breaks in the blocks of texts.

**For example, if you were to copy and paste this and press enter...**
Lorem ipsum dolor sit amet:

1) Consectetur adipiscing elit
2) Vivamus ut lacinia leo
3) Maecenas volutpat
4) Nisi in gravida hendrerit diam 

Mi tempus quam, eu iaculis turpis erat eget augue. Mauris at tortor eget felis mollis posuere quis non turpis. Quisque semper odio vel enim sollicitudin.

Vitae volutpat odio lacinia. Fusce at ligula ligula. Cras eu tincidunt elit. Sed nec dolor fringilla, efficitur nibh ac, faucibus felis.

**You would get this as your message sent:**
Lorem ipsum dolor sit amet: 1) Consectetur adipiscing elit 2) Vivamus ut lacinia leo 3) Maecenas volutpat 4) Nisi in gravida hendrerit diam Mi tempus quam, eu iaculis turpis erat eget augue. Mauris at tortor eget felis mollis posuere quis non turpis. Quisque semper odio vel enim sollicitudin.Vitae volutpat odio lacinia. Fusce at ligula ligula. Cras eu tincidunt elit. Sed nec dolor fringilla, efficitur nibh ac, faucibus felis.

**Screenshots**
<img width="1386" alt="Screenshot 2024-07-01 at 4 39 22 PM" src="https://github.com/marcolivierbouch/OpenAssistantGPT/assets/89171568/7ebabd5a-864c-4542-aed3-dbdf996aa0c8">
<img width="1386" alt="Screenshot 2024-07-01 at 4 39 30 PM" src="https://github.com/marcolivierbouch/OpenAssistantGPT/assets/89171568/02f95b25-1f08-459b-8743-a10b0a2fd167">
<img width="1386" alt="Screenshot 2024-07-01 at 4 40 09 PM" src="https://github.com/marcolivierbouch/OpenAssistantGPT/assets/89171568/b92291ba-34c4-4219-8be3-7a8ded044db2">

Thank you!

**Comment by marcolivierbouch** [comment]
I am fixing this issue https://github.com/marcolivierbouch/OpenAssistantGPT/pull/422

**Comment by marcolivierbouch** [comment]
It is fixed now!

![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/29548847/59ee12dc-857d-47af-9c7c-0c713d36c212)

**Comment by mattlawlis** [comment]
Thank you so much.  I just sent you an unrelated email regarding billing.
