### ISSUE TITLE
Copy button on embedded chatbot not working

### ISSUE THREAD

**Issue by Akhileshrangani4** [marcolivierbouch/OpenAssistantGPT#437]
Hi, I have deployed my own dashboard for personal use, when I embed my chatbot into a website, the copy button seems to not work, I have also tried the same thing with the official site and embedded the chatbot and tested it, but it is not working. The button is visible but not functional.

**Comment by marcolivierbouch** [comment]
Hello, what browser do you use?

I use chrome and it is working correctly

**Comment by Akhileshrangani4** [comment]
I also use Chrome, it works as it should on the dashboard but when embedded on the website, it seems to not work. I have tried multiple browsers and pcs, it is the same.

**Comment by marcolivierbouch** [comment]
You probably just dont have the allow="clipboard-read; clipboard-write"  in your IFRAME.

**Comment by Akhileshrangani4** [comment]
yeah that was the problem, thank you for the solution! Also, I have noticed that you have the same issue on this [page](https://github.com/marcolivierbouch/OpenAssistantGPT/blob/main/app/(dashboard)/dashboard/chatbots/%5BchatbotId%5D/embed/page.tsx) on line 101, on the embed code, add `allow="clipboard-read; clipboard-write"` to the iframe.

**Comment by marcolivierbouch** [comment]
You are right! We just updated it!

Thank you!
