### ISSUE TITLE
Getting ERR_TOO_MANY_REDIRECTS when logging in

### ISSUE THREAD

**Issue by Akhileshrangani4** [marcolivierbouch/OpenAssistantGPT#451]
Hi, I was using Linode first for hosting my custom chatbot, but I shifted to Vercel Pro plan recently and after setting everything up, I am getting this error:

![image](https://github.com/user-attachments/assets/00f70c93-304e-4656-97da-872d9286931d)

![image](https://github.com/user-attachments/assets/930e2318-d406-4071-ae83-2be20e47844a)

It is a redirect loop, but I am not sure what is causing this, have you faced this before? It was working fine when using localhost and it was fine when hosting it on linode.

Appreciate the help!

**Comment by marcolivierbouch** [comment]
This isnt an issue related to the main platform and everything is working fine on our side. We can offer paid consultation if you are interested!
