### ISSUE TITLE
Destroyed formating of assistants chat completion output

### ISSUE THREAD

**Issue by dhoegerlETM** [marcolivierbouch/OpenAssistantGPT#467]
**Describe the bug**
Since a few days the output of our integrated assistant shows a dramatic change in it's HTML formatting. We have configured our assistant via context and prompting to produce results with some dedicated structure in terms of chapters/sub-chapers and bold/regular text and lists for enumerating items.

However, currently the output does not show any chapter-structure and no lists at all.

We cannot explain the difference and even the prompt directly executed via OpenAI website (aka "playgroung") still works out correctly.

**Comment by dhoegerlETM** [comment]
@marcolivierbouch please mind this finding with highest prio as it prevents a larger roll-out on our side.

**Comment by marcolivierbouch** [comment]
Hey @dhoegerlETM,

We fixed an issue yestherday, the chatbot wasnt using the free space on the right but havent change much. When you talk about HTML formatting are you talking about when we display code in the chat or something else?


![image](https://github.com/user-attachments/assets/8ce576fe-ab62-468c-84bf-b2c2d265c2fb)

**Comment by marcolivierbouch** [comment]
is it the issue?
![image](https://github.com/user-attachments/assets/b2c01895-8dfb-4aa9-9d9e-66663125a803)

**Comment by dhoegerlETM** [comment]
> is it the issue? ![image](https://private-user-images.githubusercontent.com/29548847/353488892-b2c01895-8dfb-4aa9-9d9e-66663125a803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDg1OTEsIm5iZiI6MTcyMjM0ODI5MSwicGF0aCI6Ii8yOTU0ODg0Ny8zNTM0ODg4OTItYjJjMDE4OTUtOGRmYi00YWE5LTlkOWUtNjY2NjMxMjVhODAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE0MDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZWNlY2M0NzI1ZmFhZDZlYjI1OTVkYzRkMmVlNjU1MDU4YzdlYmJiZTk5Mzg4M2EzMGE0YjJhZmJlMmRhOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1yC3RWJE1u67uG1IHhirgu7o2Y-il95jJ8RsUG2Ik2c)

@marcolivierbouch no it itsn't about code formatting. It's more like missing chapters/titles and lists. Before we got generated answers (in your test-chat or our own embedding) like this:

![image](https://github.com/user-attachments/assets/11f88774-deda-41d2-bd9a-a0f84d91929d)

**Comment by dhoegerlETM** [comment]
@marcolivierbouch interesting - it's now working again... I looks OK now again but what could be the reason? Some differences in what OpenAI delivers?

![image](https://github.com/user-attachments/assets/0b497881-1a92-4a58-aab9-a85c4b2e647a)

**Comment by marcolivierbouch** [comment]
I had a bug during the night and I fixed it this morning the one I showed above in the screenshot, I think it was the issue.

**Comment by dhoegerlETM** [comment]
Yes, seems indeed OK again - thank you @marcolivierbouch
