### ISSUE TITLE
Tried to deploy

### ISSUE THREAD

**Issue by rossman22590** [marcolivierbouch/OpenAssistantGPT#61]
It worked on vercel, however I cannot make a bot even after scraping . Says no models available even after setting key in settings main config. 

![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/6137292/9fb99cdc-aa9c-472a-8835-5de2e03d93e8)

**Comment by marcolivierbouch** [comment]
Hi @rossman22590, you have to add the models in the database first, I showed you in the screenshot what I did!

![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/29548847/b92565cd-32ca-4b33-9fa3-66e3ad688241)

**Comment by rossman22590** [comment]
so i used vercel postgress, should i use supabase?

**Comment by rossman22590** [comment]
i have no clue how to edit this in vercel db

**Comment by rossman22590** [comment]
this worked! INSERT INTO models (id, name) VALUES 
(gen_random_uuid(), 'gpt-4-1106-preview'), 
(gen_random_uuid(), 'gpt-3.5-turbo-1106');

**Comment by rossman22590** [comment]
do i have to launch chatbotjs too?

**Comment by rossman22590** [comment]
also how to i enable the uploads ? i get [POST] /api/upload?filename=UFT_AI_Package.pdf status=400

**Comment by marcolivierbouch** [comment]
> so i used vercel postgress, should i use supabase?

You can use both of them! On my side I use supabase

**Comment by marcolivierbouch** [comment]
> do i have to launch chatbotjs too?

No you dont need but you can run the script build.sh to generate new js and then you redeploy the website

**Comment by marcolivierbouch** [comment]
> also how to i enable the uploads ? i get [POST] /api/upload?filename=UFT_AI_Package.pdf status=400

You have too enable blob storage in vercel this is where we host the files before sending them to open ai!

**Comment by marcolivierbouch** [comment]
I will make a tutorial to make sure everything is clear I have nothing rn

**Comment by rossman22590** [comment]
> > also how to i enable the uploads ? i get [POST] /api/upload?filename=UFT_AI_Package.pdf status=400
> 
> You have too enable blob storage in vercel this is where we host the files before sending them to open ai!

![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/6137292/eceae62f-6203-4e78-aa95-08be695872b0)
![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/6137292/8f27111f-6411-45cf-893c-d79e142a9822)


and it does upload but still get errors.. 
![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/6137292/8b01709b-3299-4632-b6c1-93f624b0e551)

**Comment by rossman22590** [comment]
Actual error is main.js?attr=j9ibTAbig2svWlbqbPiOUcA6Ig8CM2Su0KLHSgyOBQd8n_NuFi1RkQ84aClUApmcWRp9iKSuZWToUtUIL-mY5Z9LpvdIyy-I8gEReyQu0Kg:4215 
        
        
       POST https://mydomain.com/api/upload?filename=Why_do_postgraduate_students_commit_plagiarism_An_.pdf 400 (Bad Request)

**Comment by rossman22590** [comment]
whats weird is it does upload to blob

**Comment by marcolivierbouch** [comment]
> > > also how to i enable the uploads ? i get [POST] /api/upload?filename=UFT_AI_Package.pdf status=400
> > 
> > 
> > You have too enable blob storage in vercel this is where we host the files before sending them to open ai!
> 
> ![image](https://private-user-images.githubusercontent.com/6137292/292954593-6e27d500-7b26-4335-b89f-585ce2b573c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MjA4OTAsIm5iZiI6MTcwMzcyMDU5MCwicGF0aCI6Ii82MTM3MjkyLzI5Mjk1NDU5My02ZTI3ZDUwMC03YjI2LTQzMzUtYjg5Zi01ODVjZTJiNTczYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMjM0MzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjViYjQyNGFhYmFjM2E4NDU0NGY3NWFiZjFlZDk0NWVjODljZjY0YzE3NTMzMDUzNDdhMWZlMDNkOTk3YTViZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JpDEYguM4KzeqXrXyeRoGQVNSmAubaJmrBROQQPg5v8)
> 
> ![image](https://private-user-images.githubusercontent.com/6137292/292954448-8f27111f-6411-45cf-893c-d79e142a9822.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MjA4OTAsIm5iZiI6MTcwMzcyMDU5MCwicGF0aCI6Ii82MTM3MjkyLzI5Mjk1NDQ0OC04ZjI3MTExZi02NDExLTQ1Y2YtODkzYy1kNzllMTQyYTk4MjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMjM0MzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmIwMTM4ZWVmMTEyMDNiNDFjZmI0MDBiMjVjMzkxYTA0YzBhZmU1NmUyZTQxNjNiNTdlZTE5ZDk3MDYyMDRiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OBf1NoQi2ZwRjugdiXzkZRn8mGrmTqEp3-6yurkkaYs)
> 
> and it does upload but still get errors.. ![image](https://private-user-images.githubusercontent.com/6137292/292954496-8b01709b-3299-4632-b6c1-93f624b0e551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MjA4OTAsIm5iZiI6MTcwMzcyMDU5MCwicGF0aCI6Ii82MTM3MjkyLzI5Mjk1NDQ5Ni04YjAxNzA5Yi0zMjk5LTQ2MzItYjZjMS05M2Y2MjRiMGU1NTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMjM0MzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDZlYjg3M2VmNjU5OTg0ZmMyMWY2Nzk5ZjQ1MWJlYTNlMzk5MWI4OTcyNGIxNDBjNjRlNzQ5NzRiMGNlYTE5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Z0W7eN8pGR4NtI9uQtoEMNSqKMzNqn9E4R82RH_X8Zc)

When we upload a file it also does upload to OpenAI so the error is probably related to openai. You probably have more information in the logs!

Can you show me the logs?

**Comment by rossman22590** [comment]
I fixed this!!! :)

**Comment by marcolivierbouch** [comment]
Glad you were able to fix all issues!
