### ISSUE TITLE
Can not add API KEY

### ISSUE THREAD

**Issue by narinderkmaurya** [marcolivierbouch/OpenAssistantGPT#95]
**Describe the bug**
When typing our OPEN AI key, the save logo is stuck at loading

**Expected behavior**
Can expect a toast that it has been accepted

**Screenshots**
![image](https://github.com/marcolivierbouch/OpenAssistantGPT/assets/96182171/b7cbe01c-5a00-44aa-83a8-b31a74b5ff05)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Brave]

**Comment by marcolivierbouch** [comment]
Hey @narinderkmaurya,

I would recommend you to delete your API since everyone can see it here :) 

I don't see any error in the backend votre profile configuration. Do you have any error in your browser?
